/*
 * generated by Xtext 2.28.0.M1
 */
package hellojava.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HelloJavaUiModule extends AbstractHelloJavaUiModule {

	public HelloJavaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
