/*
 * generated by Xtext 2.28.0.M1
 */
package hellojava.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hellojava.HelloJavaRuntimeModule;
import hellojava.HelloJavaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HelloJavaIdeSetup extends HelloJavaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HelloJavaRuntimeModule(), new HelloJavaIdeModule()));
	}
	
}
