/*
 * generated by Xtext 2.28.0.M1
 */
package hellojava;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HelloJavaStandaloneSetup extends HelloJavaStandaloneSetupGenerated {

	public static void doSetup() {
		new HelloJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
