/*
 * generated by Xtext 2.28.0.M1
 */
package hellojava;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HelloJavaRuntimeModule extends AbstractHelloJavaRuntimeModule {
}
